### ISSUE TITLE
yolox使用自己训练的模型推理不出

### ISSUE THREAD

**Issue by Zcty-L** [Linaom1214/TensorRT-For-YOLO-Series#10]

**Comment by Zcty-L** [comment]
Jetson nano平台

**Comment by Linaom1214** [comment]
可以提供一下onnx文件吗？ yolox 的demo搞的比较早 可以把图像的均值和方差设为None 先试试

**Comment by Linaom1214** [comment]
> Jetson nano平台
似乎你的输入搞错了 我看了一些模型是 416 * 410 注释掉归一化是正确的

**Comment by Linaom1214** [comment]
> _No description provided._

新版本修复了这个问题：

使用YOLOX模型时 请注释掉

```
    padded_img = padded_img[:, :, ::-1]
    padded_img /= 255.0
```

https://github.com/Linaom1214/TensorRT-For-YOLO-Series/blob/adc89037992522d81d3ca349edad62eecf7edd9e/utils/utils.py#L201

**Comment by leomy9527** [comment]
> 可以提供一下onnx文件吗？ yolox 的demo搞的比较早 可以把图像的均值和方差设为None 先试试

[yolox.zip](https://github.com/Linaom1214/TensorRT-For-YOLO-Series/files/13843654/yolox.zip)
你能帮我看看这个文件吗 怎么输出的图像位置不对 应该是416 2lab

**Comment by leomy9527** [comment]
> 可以提供一下onnx文件吗？ yolox 的demo搞的比较早 可以把图像的均值和方差设为None 先试试

[yolox.zip](https://github.com/Linaom1214/TensorRT-For-YOLO-Series/files/13843807/yolox.zip)
能帮我看下这个文件吗  416 2lab 输出框都在顶部 谢谢
