### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by moooises** [Linaom1214/TensorRT-For-YOLO-Series#115]
Hello,
What is the license of this respository? Currently there is none.
According to [Github rules](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository), if there isn't any license, the repository isn't Open Source neither Free. 
However, I wanted to ask first to be sure.
Thanks.

**Comment by moooises** [comment]
?

**Comment by Linaom1214** [comment]
> ?

this repo is free, please enjoy it!.

**Comment by moooises** [comment]
I asked  just to be sure if I can use the code of this repo as it is or modifying it in a commercial software or company .
Is it ok to use this repo in those cases? Giving proper credit, of course.

**Comment by Linaom1214** [comment]
> I asked just to be sure if I can use the code of this repo as it is or modifying it in a commercial software or company . Is it ok to use this repo in those cases? Giving proper credit, of course.

yes
