### ISSUE TITLE
 TensorRT Conversion Issue  "TypeError: pybind11::init(): factory function returned nullptr"

### ISSUE THREAD

**Issue by VbsmRobotic** [Linaom1214/TensorRT-For-YOLO-Series#117]
Hi,

I ran the ONNX to TensorRT conversion using the following command:

$ python3 export.py -o yolov7-tiny.onnx -e yolov7-tiny-nms.trt -p fp16

However, I encountered the following issue:

Namespace(calib_batch_size=8, calib_cache='./calibration.cache', calib_input=None, calib_num_images=5000, conf_thres=0.4, end2end=False, engine='yolov7-tiny-nms.trt', iou_thres=0.5, max_det=100, onnx='/home/vahid/aid_ws/GitHub-Vbsm/YOLO/PyTorch-ONNX-TensorRT/yolov7-WingKinYiu/yolov7-tiny.onnx', precision='fp16', v8=False, verbose=False, workspace=1)
[12/26/2023-13:37:00] [TRT] [W] Unable to determine GPU memory usage
[12/26/2023-13:37:00] [TRT] [W] Unable to determine GPU memory usage
[12/26/2023-13:37:00] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 23, GPU 0 (MiB)
[12/26/2023-13:37:00] [TRT] [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Traceback (most recent call last):
  File "export.py", line 308, in <module>
    main(args)
  File "export.py", line 266, in main
    builder = EngineBuilder(args.verbose, args.workspace)
  File "export.py", line 107, in __init__
    self.builder = trt.Builder(self.trt_logger)
TypeError: pybind11::init(): factory function returned nullptr

Here are the Python environment dependencies:

$ python3
Python 3.6.9 (default, Mar 10 2023, 16:46:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.10.1+cu102
>>> import torchvision
>>> print(torchvision.__version__)
0.11.2+cu102
>>> import onnx
>>> print(onnx.__version__)
1.8.1
>>> import pycuda
>>> import tensorrt
>>> print(tensorrt.__version__)
8.6.1
>>> exit()

I would appreciate any advice or solutions you can provide to resolve this issue. Thank you.

**Comment by Linaom1214** [comment]
> Hi,
> 
> I ran the ONNX to TensorRT conversion using the following command:
> 
> $ python3 export.py -o yolov7-tiny.onnx -e yolov7-tiny-nms.trt -p fp16
> 
> However, I encountered the following issue:
> 
> Namespace(calib_batch_size=8, calib_cache='./calibration.cache', calib_input=None, calib_num_images=5000, conf_thres=0.4, end2end=False, engine='yolov7-tiny-nms.trt', iou_thres=0.5, max_det=100, onnx='/home/vahid/aid_ws/GitHub-Vbsm/YOLO/PyTorch-ONNX-TensorRT/yolov7-WingKinYiu/yolov7-tiny.onnx', precision='fp16', v8=False, verbose=False, workspace=1) [12/26/2023-13:37:00] [TRT] [W] Unable to determine GPU memory usage [12/26/2023-13:37:00] [TRT] [W] Unable to determine GPU memory usage [12/26/2023-13:37:00] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 23, GPU 0 (MiB) [12/26/2023-13:37:00] [TRT] [W] CUDA initialization failure with error: 35. Please check your CUDA installation: http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html Traceback (most recent call last): File "export.py", line 308, in main(args) File "export.py", line 266, in main builder = EngineBuilder(args.verbose, args.workspace) File "export.py", line 107, in **init** self.builder = trt.Builder(self.trt_logger) TypeError: pybind11::init(): factory function returned nullptr
> 
> Here are the Python environment dependencies:
> 
> $ python3 Python 3.6.9 (default, Mar 10 2023, 16:46:00) [GCC 8.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import torch
> > > > print(torch.**version**)
> > > > 1.10.1+cu102
> > > > import torchvision
> > > > print(torchvision.**version**)
> > > > 0.11.2+cu102
> > > > import onnx
> > > > print(onnx.**version**)
> > > > 1.8.1
> > > > import pycuda
> > > > import tensorrt
> > > > print(tensorrt.**version**)
> > > > 8.6.1
> > > > exit()
> 
> I would appreciate any advice or solutions you can provide to resolve this issue. Thank you.

you can try this branch, https://github.com/Linaom1214/TensorRT-For-YOLO-Series/tree/cuda-python, this error may occur by pycuda, or change the pycuda version.

**Comment by VbsmRobotic** [comment]
Thank you for your advice; I've addressed the issue.
