### ISSUE TITLE
yolox和yolov7的官方代码似乎已经做了nms onnx推理

### ISSUE THREAD

**Issue by NeKoooo233** [Linaom1214/TensorRT-For-YOLO-Series#127]
https://github.com/Megvii-BaseDetection/YOLOX/pull/1113
https://github.com/WongKinYiu/yolov7/blob/main/export.py
line 34

**Comment by Linaom1214** [comment]
https://github.com/WongKinYiu/yolov7/commits?author=Linaom1214 

是的，本项目只是提供了一种不依赖于第三方库的nms plugin 插入方式。
