### ISSUE TITLE
Does this support dynamic batch input convert?

### ISSUE THREAD

**Issue by jlcbj** [Linaom1214/TensorRT-For-YOLO-Series#131]
Input 'images' with shape (-1, 3, -1, -1) and dtype DataType.FLOAT
Output 'output0' with shape (-1, 300, 6) and dtype DataType.FLOAT
Traceback (most recent call last):
  File "D:\project\TensorRT-For-YOLO-Series\export.py", line 363, in <module>
    main(args)
  File "D:\project\TensorRT-For-YOLO-Series\export.py", line 320, in main
    builder.create_network(args.onnx, args.end2end, args.conf_thres, args.iou_thres, args.max_det, v8=args.v8, v10=args.v10)
  File "D:\project\TensorRT-For-YOLO-Series\export.py", line 145, in create_network
    assert self.batch_size > 0
AssertionError
![yolov10m](https://github.com/Linaom1214/TensorRT-For-YOLO-Series/assets/6059104/e94cfc9e-74f9-49be-b254-7ba7db5c0803)

**Comment by Linaom1214** [comment]
@jlcbj  this repo now only support one batch.

**Comment by jlcbj** [comment]
ok, I use offical yolov10 repo resolve this issue

**Comment by Linaom1214** [comment]
@jlcbj  can you send the onnx file to my mail？ I will check this error！ my email is linaom1214@163.com

**Comment by jlcbj** [comment]
链接：https://pan.baidu.com/s/1_8saWFxG4JfQtc9nHF_-zw?pwd=cbqr 
提取码：cbqr 
onnx file for yolov10s,fp16

now convert to trt through container nvcr.io/nvidia/tensorrt:23.07-py3

trtexec --onnx=/models/yolo10s_onnx_fp16/1/model.onnx --saveEngine=/models/yolo10s_onnx_fp16/1/model.plan --explicitBatch --minShapes=images:1x3x640x640 --optShapes=images:16x3x640x640 --maxShapes=images:32x3x640x640 --workspace=1024 --fp16

**Comment by jlcbj** [comment]
链接：https://pan.baidu.com/s/1_8saWFxG4JfQtc9nHF_-zw?pwd=cbqr 
提取码：cbqr 
onnx file for yolov10s,fp16

now convert to trt through container nvcr.io/nvidia/tensorrt:23.07-py3

trtexec --onnx=/models/yolo10s_onnx_fp16/1/model.onnx --saveEngine=/models/yolo10s_onnx_fp16/1/model.plan --explicitBatch --minShapes=images:1x3x640x640 --optShapes=images:16x3x640x640 --maxShapes=images:32x3x640x640 --workspace=1024 --fp16
