### ISSUE TITLE
yolov7tiny转换到trt后无法正常运行

### ISSUE THREAD

**Issue by 587687525** [Linaom1214/TensorRT-For-YOLO-Series#34]

**Comment by 587687525** [comment]
报错日志：
G:\Anaconda3\python.exe G:\AICode\PtilopsisAim\tensorrt-python\trt.py
G:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)
Traceback (most recent call last):
  File "\tensorrt-python\trt.py", line 22, in <module>
    origin_img = pred.inference(img_path, conf=0.3)
  File "\tensorrt-python\utils\utils.py", line 99, in inference
    predictions = np.reshape(data, (1, -1, int(5+self.n_classes)))[0]
  File "<__array_function__ internals>", line 180, in reshape
  File "G:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "G:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "G:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 4 into shape (1,newaxis,7)

进程已结束,退出代码1

**Comment by Linaom1214** [comment]
> 报错日志： G:\Anaconda3\python.exe \tensorrt-python\trt.py G:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray. result = getattr(asarray(obj), method)(*args, **kwds) Traceback (most recent call last): File "\tensorrt-python\trt.py", line 22, in origin_img = pred.inference(img_path, conf=0.3) File "\tensorrt-python\utils\utils.py", line 99, in inference predictions = np.reshape(data, (1, -1, int(5+self.n_classes)))[0] File "<**array_function** internals>", line 180, in reshape File "G:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape return _wrapfunc(a, 'reshape', newshape, order=order) File "G:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 54, in _wrapfunc return _wrapit(obj, method, *args, **kwds) File "G:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 43, in _wrapit result = getattr(asarray(obj), method)(*args, **kwds) ValueError: cannot reshape array of size 4 into shape (1,newaxis,7)
> 
> 进程已结束,退出代码1

这是因为你使用了end2end模型，然后没有将推理文件中的 detect 的end2end 标识传入，可以使用 `detetct(img. conf, end2end=True)`解决，或者拉最新的代码 我有个问题哈， 是我写的文档写的太烂了吗？（仅交流可以提供一些改进意见），
感觉大家都不读文档的

**Comment by 587687525** [comment]
我看见了这一行提示。我记得我在运行时将两个end2end的default值都设置为了false，或许是我记错了

**Comment by Linaom1214** [comment]
> 我看见了这一行提示。我记得我在运行时将两个end2end的default值都设置为了false，或许是我记错了

是最新的代码吗？ 还有问题吗？

**Comment by 587687525** [comment]
已经拉取了最新的代码，num_cls是2，都检查过了，现在没有问题啦，非常非常感谢(〃'▽'〃)

**Comment by Linaom1214** [comment]
> 已经拉取了最新的代码，num_cls是2，都检查过了，现在没有问题啦，非常非常感谢(〃'▽'〃)

好的，没有问题就好， 在线求start

**Comment by 587687525** [comment]
ok，星星+1
