### ISSUE TITLE
C++ script shows nothing

### ISSUE THREAD

**Issue by naserpiltan** [Linaom1214/TensorRT-For-YOLO-Series#38]
I used the commands int the official repository of the yolov7 [(here)](https://github.com/WongKinYiu/yolov7) to convert the yolov7_tiny.py to a TensorRT model.
I converted the yolov7.pt to yolov7-tiny.onnx with this command:
```
python export.py --weights ./yolov7-tiny.pt --grid --end2end --simplify --topk-all 100 --iou-thres 0.65 --conf-thres 0.35 --img-size 640 640
```
 And then converted the yolov7-tiny.onnx model to the TensorRT model (yolov7-tiny-nms.trt )with this command:
 ```
git clone https://github.com/Linaom1214/tensorrt-python.git
python ./tensorrt-python/export.py -o yolov7-tiny.onnx -e yolov7-tiny-nms.trt -p fp16
```
 I used the file  cpp/end2end/main.cpp to inference, but got no result. This is the output on my terminal:

> model size: 37371054
Registered plugin creator - ::GridAnchor_TRT version 1
Registered plugin creator - ::GridAnchorRect_TRT version 1
Registered plugin creator - ::NMS_TRT version 1
Registered plugin creator - ::Reorg_TRT version 1
Registered plugin creator - ::Region_TRT version 1
Registered plugin creator - ::Clip_TRT version 1
Registered plugin creator - ::LReLU_TRT version 1
Registered plugin creator - ::PriorBox_TRT version 1
Registered plugin creator - ::Normalize_TRT version 1
Registered plugin creator - ::ScatterND version 1
Registered plugin creator - ::RPROI_TRT version 1
Registered plugin creator - ::BatchedNMS_TRT version 1
Registered plugin creator - ::BatchedNMSDynamic_TRT version 1
Registered plugin creator - ::BatchTilePlugin_TRT version 1
Registered plugin creator - ::FlattenConcat_TRT version 1
Registered plugin creator - ::CropAndResize version 1
Registered plugin creator - ::CropAndResizeDynamic version 1
Registered plugin creator - ::DetectionLayer_TRT version 1
Registered plugin creator - ::EfficientNMS_TRT version 1
Registered plugin creator - ::EfficientNMS_ONNX_TRT version 1
Registered plugin creator - ::EfficientNMS_Explicit_TF_TRT version 1
Registered plugin creator - ::EfficientNMS_Implicit_TF_TRT version 1
Registered plugin creator - ::ProposalDynamic version 1
Registered plugin creator - ::Proposal version 1
Registered plugin creator - ::ProposalLayer_TRT version 1
Registered plugin creator - ::PyramidROIAlign_TRT version 1
Registered plugin creator - ::ResizeNearest_TRT version 1
Registered plugin creator - ::Split version 1
Registered plugin creator - ::SpecialSlice_TRT version 1
Registered plugin creator - ::InstanceNormalization_TRT version 1
Registered plugin creator - ::InstanceNormalization_TRT version 2
Registered plugin creator - ::CoordConvAC version 1
Registered plugin creator - ::DecodeBbox3DPlugin version 1
Registered plugin creator - ::GenerateDetection_TRT version 1
Registered plugin creator - ::MultilevelCropAndResize_TRT version 1
Registered plugin creator - ::MultilevelProposeROI_TRT version 1
Registered plugin creator - ::NMSDynamic_TRT version 1
Registered plugin creator - ::PillarScatterPlugin version 1
Registered plugin creator - ::VoxelGeneratorPlugin version 1
Registered plugin creator - ::MultiscaleDeformableAttnPlugin_TRT version 1
> Using cublas as a tactic source
> Using cuDNN as a tactic source
> Deserialization required 472693 microseconds.
> 3: Cannot find binding of given name: image_arrays
> 3: [engine.cpp::getBindingDimensions::1305] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/engine.cpp::getBindingDimensions::1305, condition: bindIndex >= 0 && bindIndex < getNbBindings()
> )
> 3: Cannot find binding of given name: num
> 3: [engine.cpp::getBindingDimensions::1305] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/engine.cpp::getBindingDimensions::1305, condition: bindIndex >= 0 && bindIndex < getNbBindings()
> )
> 3: Cannot find binding of given name: boxes
> 3: [engine.cpp::getBindingDimensions::1305] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/engine.cpp::getBindingDimensions::1305, condition: bindIndex >= 0 && bindIndex < getNbBindings()
> )
> 3: Cannot find binding of given name: scores
> 3: [engine.cpp::getBindingDimensions::1305] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/engine.cpp::getBindingDimensions::1305, condition: bindIndex >= 0 && bindIndex < getNbBindings()
> )
> 3: Cannot find binding of given name: classes
> 3: [engine.cpp::getBindingDimensions::1305] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/engine.cpp::getBindingDimensions::1305, condition: bindIndex >= 0 && bindIndex < getNbBindings()
> )
> Using cublas as a tactic source
> Using cuDNN as a tactic source
> Total per-runner device persistent memory is 1428480
> Total per-runner host persistent memory is 115152
> Allocated activation device memory of size 66407424

It seems some of the bindings can not be done by the model.

**Comment by Linaom1214** [comment]
> 

please pull the newest code 

recommend use follow  method convert the model.


```
!python yolov7/export.py --weights yolov7-tiny.pt --grid  --simplify
!python export.py -o yolov7-tiny.onnx -e yolov7-tiny.trt --end2end
!python trt.py -e yolov7-tiny.trt  -i src/1.jpg -o yolov7-tiny-1.jpg --end2end
```

**Comment by Linaom1214** [comment]
> > 
> 
> please pull the newest code
> 
> recommend use follow method convert the model.
> 
> ```
> !python yolov7/export.py --weights yolov7-tiny.pt --grid  --simplify
> !python export.py -o yolov7-tiny.onnx -e yolov7-tiny.trt --end2end
> !python trt.py -e yolov7-tiny.trt  -i src/1.jpg -o yolov7-tiny-1.jpg --end2end
> ```

## With NMS Plugin

**Edit code for your model**

```c++
auto in_dims = engine->getBindingDimensions(engine->getBindingIndex("image")); 
```
**run**

```shell
cd end2end && mkdir build && build
cmake ..
make
./yolo -model_path  engine   -image_path xxx.jpg
```

**Comment by naserpiltan** [comment]
I appreciate your response. I'm using the last update of the repository and in order to verify everything works fine, I'm using the official yolov7_tiny.pt.
I did what you said but still have this error and there are no detections  :

```
Using cublas as a tactic source
Using cuDNN as a tactic source
Deserialization required 476274 microseconds.
3: Cannot find binding of given name: image_arrays
3: [engine.cpp::getBindingDimensions::1305] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/engine.cpp::getBindingDimensions::1305, condition: bindIndex >= 0 && bindIndex < getNbBindings()
)
Using cublas as a tactic source
Using cuDNN as a tactic source
Total per-runner device persistent memory is 1428480
Total per-runner host persistent memory is 113120
Allocated activation device memory of size 65997824
12ms
```

**Comment by naserpiltan** [comment]
In python it works just fine.

**Comment by naserpiltan** [comment]
> I appreciate your response. I'm using the last update of the repository and in order to verify everything works fine, I'm using the official yolov7_tiny.pt. I did what you said but still have this error and there are no detections :
> 
> ```
> Using cublas as a tactic source
> Using cuDNN as a tactic source
> Deserialization required 476274 microseconds.
> 3: Cannot find binding of given name: image_arrays
> 3: [engine.cpp::getBindingDimensions::1305] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/engine.cpp::getBindingDimensions::1305, condition: bindIndex >= 0 && bindIndex < getNbBindings()
> )
> Using cublas as a tactic source
> Using cuDNN as a tactic source
> Total per-runner device persistent memory is 1428480
> Total per-runner host persistent memory is 113120
> Allocated activation device memory of size 65997824
> 12ms
> ```

In python this weight detects and works just fine, but C++ is faulty .

**Comment by Linaom1214** [comment]
> > I appreciate your response. I'm using the last update of the repository and in order to verify everything works fine, I'm using the official yolov7_tiny.pt. I did what you said but still have this error and there are no detections :
> > ```
> > Using cublas as a tactic source
> > Using cuDNN as a tactic source
> > Deserialization required 476274 microseconds.
> > 3: Cannot find binding of given name: image_arrays
> > 3: [engine.cpp::getBindingDimensions::1305] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/engine.cpp::getBindingDimensions::1305, condition: bindIndex >= 0 && bindIndex < getNbBindings()
> > )
> > Using cublas as a tactic source
> > Using cuDNN as a tactic source
> > Total per-runner device persistent memory is 1428480
> > Total per-runner host persistent memory is 113120
> > Allocated activation device memory of size 65997824
> > 12ms
> > ```
> 
> In python this weight detects and works just fine, but C++ is faulty .

use netron https://netron.app/ check the input and out output name of your model

**Comment by naserpiltan** [comment]
Thank you sir. I solved the problem. It needed to be as follows:
 auto in_dims = engine->getBindingDimensions(engine->getBindingIndex("images"));
