### ISSUE TITLE
Why does Python use the TRT model to identify normal results, but C + + recognizes 0 objects. The same model file is used

### ISSUE THREAD

**Issue by YFforever2022** [Linaom1214/TensorRT-For-YOLO-Series#40]
Why does Python use the TRT model to identify normal results, but C + + recognizes 0 objects. The same model file is used
![1](https://user-images.githubusercontent.com/111646263/185751246-d9ba9728-5ff1-4157-b546-888e560dfc27.jpg)
![2](https://user-images.githubusercontent.com/111646263/185751250-ae21a70a-55de-4fdd-a644-d671ba9840dd.jpg)
![3](https://user-images.githubusercontent.com/111646263/185751251-8fb83b26-af2c-42cc-a672-a20154b39f0b.jpg)

**Comment by YFforever2022** [comment]
[https://github.com/WongKinYiu/yolov7](url)Use the export of this project
python export.py --weights yolov7-tiny.pt --grid --simplify

Project configuration environment
python3.8.9
VS2019
opencv4.6
cuda_10.2.89_441.22_win10.exe
cudnn-windows-x86_64-8.4.1.50_cuda10.2-archive.zip
TensorRT-8.4.1.5

**Comment by Linaom1214** [comment]
> [https://github.com/WongKinYiu/yolov7](url)Use the export of this project python export.py --weights yolov7-tiny.pt --grid --simplify
> 
> Project configuration environment python3.8.9 VS2019 opencv4.6 cuda_10.2.89_441.22_win10.exe cudnn-windows-x86_64-8.4.1.50_cuda10.2-archive.zip TensorRT-8.4.1.5

https://github.com/Linaom1214/TensorRT-For-YOLO-Series/tree/main/cpp

you choice a end2end cpp file but use the model which without nms plugin

**Comment by Linaom1214** [comment]
https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/38

**Comment by YFforever2022** [comment]
[https://github.com/Linaom1214/TensorRT-For-YOLO-Series](url)

I use this project. The command is python export.py -o yolov7-tiny.onnx -e yolov7-tiny.trt --end2end

It is an NMS plugin

**Comment by YFforever2022** [comment]
Using netron, I found that inputname and outputname are different. Now I'm trying to correct them

**Comment by YFforever2022** [comment]
Thank you, sir. I used the same method to solve this problem. It needs to be modified as follows: Auto in_ dims = engine->getBindingDimensions(engine->getBindingIndex("images"));

model size: 32443323
Registered plugin creator - ::GridAnchor_TRT version 1
Registered plugin creator - ::GridAnchorRect_TRT version 1
Registered plugin creator - ::NMS_TRT version 1
Registered plugin creator - ::Reorg_TRT version 1
Registered plugin creator - ::Region_TRT version 1
Registered plugin creator - ::Clip_TRT version 1
Registered plugin creator - ::LReLU_TRT version 1
Registered plugin creator - ::PriorBox_TRT version 1
Registered plugin creator - ::Normalize_TRT version 1
Registered plugin creator - ::ScatterND version 1
Registered plugin creator - ::RPROI_TRT version 1
Registered plugin creator - ::BatchedNMS_TRT version 1
Registered plugin creator - ::BatchedNMSDynamic_TRT version 1
Registered plugin creator - ::BatchTilePlugin_TRT version 1
Registered plugin creator - ::FlattenConcat_TRT version 1
Registered plugin creator - ::CropAndResize version 1
Registered plugin creator - ::CropAndResizeDynamic version 1
Registered plugin creator - ::DetectionLayer_TRT version 1
Registered plugin creator - ::EfficientNMS_TRT version 1
Registered plugin creator - ::EfficientNMS_ONNX_TRT version 1
Registered plugin creator - ::EfficientNMS_Explicit_TF_TRT version 1
Registered plugin creator - ::EfficientNMS_Implicit_TF_TRT version 1
Registered plugin creator - ::ProposalDynamic version 1
Registered plugin creator - ::Proposal version 1
Registered plugin creator - ::ProposalLayer_TRT version 1
Registered plugin creator - ::PyramidROIAlign_TRT version 1
Registered plugin creator - ::ResizeNearest_TRT version 1
Registered plugin creator - ::Split version 1
Registered plugin creator - ::SpecialSlice_TRT version 1
Registered plugin creator - ::InstanceNormalization_TRT version 1
Registered plugin creator - ::InstanceNormalization_TRT version 2
Registered plugin creator - ::CoordConvAC version 1
Registered plugin creator - ::DecodeBbox3DPlugin version 1
Registered plugin creator - ::GenerateDetection_TRT version 1
Registered plugin creator - ::MultilevelCropAndResize_TRT version 1
Registered plugin creator - ::MultilevelProposeROI_TRT version 1
Registered plugin creator - ::NMSDynamic_TRT version 1
Registered plugin creator - ::PillarScatterPlugin version 1
Registered plugin creator - ::VoxelGeneratorPlugin version 1
Registered plugin creator - ::MultiscaleDeformableAttnPlugin_TRT version 1
Using cublas as a tactic source
Using cuDNN as a tactic source
Deserialization required 402759 microseconds.
Using cublas as a tactic source
Using cuDNN as a tactic source
Total per-runner device persistent memory is 1420800
Total per-runner host persistent memory is 108288
Allocated activation device memory of size 65997824
20ms

Now I have the correct reasoning picture

**Comment by Linaom1214** [comment]
> Thank you, sir. I used the same method to solve this problem. It needs to be modified as follows: Auto in_ dims = engine->getBindingDimensions(engine->getBindingIndex("images"));
> 
> model size: 32443323 Registered plugin creator - ::GridAnchor_TRT version 1 Registered plugin creator - ::GridAnchorRect_TRT version 1 Registered plugin creator - ::NMS_TRT version 1 Registered plugin creator - ::Reorg_TRT version 1 Registered plugin creator - ::Region_TRT version 1 Registered plugin creator - ::Clip_TRT version 1 Registered plugin creator - ::LReLU_TRT version 1 Registered plugin creator - ::PriorBox_TRT version 1 Registered plugin creator - ::Normalize_TRT version 1 Registered plugin creator - ::ScatterND version 1 Registered plugin creator - ::RPROI_TRT version 1 Registered plugin creator - ::BatchedNMS_TRT version 1 Registered plugin creator - ::BatchedNMSDynamic_TRT version 1 Registered plugin creator - ::BatchTilePlugin_TRT version 1 Registered plugin creator - ::FlattenConcat_TRT version 1 Registered plugin creator - ::CropAndResize version 1 Registered plugin creator - ::CropAndResizeDynamic version 1 Registered plugin creator - ::DetectionLayer_TRT version 1 Registered plugin creator - ::EfficientNMS_TRT version 1 Registered plugin creator - ::EfficientNMS_ONNX_TRT version 1 Registered plugin creator - ::EfficientNMS_Explicit_TF_TRT version 1 Registered plugin creator - ::EfficientNMS_Implicit_TF_TRT version 1 Registered plugin creator - ::ProposalDynamic version 1 Registered plugin creator - ::Proposal version 1 Registered plugin creator - ::ProposalLayer_TRT version 1 Registered plugin creator - ::PyramidROIAlign_TRT version 1 Registered plugin creator - ::ResizeNearest_TRT version 1 Registered plugin creator - ::Split version 1 Registered plugin creator - ::SpecialSlice_TRT version 1 Registered plugin creator - ::InstanceNormalization_TRT version 1 Registered plugin creator - ::InstanceNormalization_TRT version 2 Registered plugin creator - ::CoordConvAC version 1 Registered plugin creator - ::DecodeBbox3DPlugin version 1 Registered plugin creator - ::GenerateDetection_TRT version 1 Registered plugin creator - ::MultilevelCropAndResize_TRT version 1 Registered plugin creator - ::MultilevelProposeROI_TRT version 1 Registered plugin creator - ::NMSDynamic_TRT version 1 Registered plugin creator - ::PillarScatterPlugin version 1 Registered plugin creator - ::VoxelGeneratorPlugin version 1 Registered plugin creator - ::MultiscaleDeformableAttnPlugin_TRT version 1 Using cublas as a tactic source Using cuDNN as a tactic source Deserialization required 402759 microseconds. Using cublas as a tactic source Using cuDNN as a tactic source Total per-runner device persistent memory is 1420800 Total per-runner host persistent memory is 108288 Allocated activation device memory of size 65997824 20ms
> 
> Now I have the correct reasoning picture

yes ! if this reop is helpful for your work, Could you give me a free star

**Comment by YFforever2022** [comment]
> > Thank you, sir. I used the same method to solve this problem. It needs to be modified as follows: Auto in_ dims = engine->getBindingDimensions(engine->getBindingIndex("images"));
> > model size: 32443323 Registered plugin creator - ::GridAnchor_TRT version 1 Registered plugin creator - ::GridAnchorRect_TRT version 1 Registered plugin creator - ::NMS_TRT version 1 Registered plugin creator - ::Reorg_TRT version 1 Registered plugin creator - ::Region_TRT version 1 Registered plugin creator - ::Clip_TRT version 1 Registered plugin creator - ::LReLU_TRT version 1 Registered plugin creator - ::PriorBox_TRT version 1 Registered plugin creator - ::Normalize_TRT version 1 Registered plugin creator - ::ScatterND version 1 Registered plugin creator - ::RPROI_TRT version 1 Registered plugin creator - ::BatchedNMS_TRT version 1 Registered plugin creator - ::BatchedNMSDynamic_TRT version 1 Registered plugin creator - ::BatchTilePlugin_TRT version 1 Registered plugin creator - ::FlattenConcat_TRT version 1 Registered plugin creator - ::CropAndResize version 1 Registered plugin creator - ::CropAndResizeDynamic version 1 Registered plugin creator - ::DetectionLayer_TRT version 1 Registered plugin creator - ::EfficientNMS_TRT version 1 Registered plugin creator - ::EfficientNMS_ONNX_TRT version 1 Registered plugin creator - ::EfficientNMS_Explicit_TF_TRT version 1 Registered plugin creator - ::EfficientNMS_Implicit_TF_TRT version 1 Registered plugin creator - ::ProposalDynamic version 1 Registered plugin creator - ::Proposal version 1 Registered plugin creator - ::ProposalLayer_TRT version 1 Registered plugin creator - ::PyramidROIAlign_TRT version 1 Registered plugin creator - ::ResizeNearest_TRT version 1 Registered plugin creator - ::Split version 1 Registered plugin creator - ::SpecialSlice_TRT version 1 Registered plugin creator - ::InstanceNormalization_TRT version 1 Registered plugin creator - ::InstanceNormalization_TRT version 2 Registered plugin creator - ::CoordConvAC version 1 Registered plugin creator - ::DecodeBbox3DPlugin version 1 Registered plugin creator - ::GenerateDetection_TRT version 1 Registered plugin creator - ::MultilevelCropAndResize_TRT version 1 Registered plugin creator - ::MultilevelProposeROI_TRT version 1 Registered plugin creator - ::NMSDynamic_TRT version 1 Registered plugin creator - ::PillarScatterPlugin version 1 Registered plugin creator - ::VoxelGeneratorPlugin version 1 Registered plugin creator - ::MultiscaleDeformableAttnPlugin_TRT version 1 Using cublas as a tactic source Using cuDNN as a tactic source Deserialization required 402759 microseconds. Using cublas as a tactic source Using cuDNN as a tactic source Total per-runner device persistent memory is 1420800 Total per-runner host persistent memory is 108288 Allocated activation device memory of size 65997824 20ms
> > Now I have the correct reasoning picture
> 
> yes ! if this reop is helpful for your work, Could you give me a free star

of course

**Comment by Linaom1214** [comment]
> > > Thank you, sir. I used the same method to solve this problem. It needs to be modified as follows: Auto in_ dims = engine->getBindingDimensions(engine->getBindingIndex("images"));
> > > model size: 32443323 Registered plugin creator - ::GridAnchor_TRT version 1 Registered plugin creator - ::GridAnchorRect_TRT version 1 Registered plugin creator - ::NMS_TRT version 1 Registered plugin creator - ::Reorg_TRT version 1 Registered plugin creator - ::Region_TRT version 1 Registered plugin creator - ::Clip_TRT version 1 Registered plugin creator - ::LReLU_TRT version 1 Registered plugin creator - ::PriorBox_TRT version 1 Registered plugin creator - ::Normalize_TRT version 1 Registered plugin creator - ::ScatterND version 1 Registered plugin creator - ::RPROI_TRT version 1 Registered plugin creator - ::BatchedNMS_TRT version 1 Registered plugin creator - ::BatchedNMSDynamic_TRT version 1 Registered plugin creator - ::BatchTilePlugin_TRT version 1 Registered plugin creator - ::FlattenConcat_TRT version 1 Registered plugin creator - ::CropAndResize version 1 Registered plugin creator - ::CropAndResizeDynamic version 1 Registered plugin creator - ::DetectionLayer_TRT version 1 Registered plugin creator - ::EfficientNMS_TRT version 1 Registered plugin creator - ::EfficientNMS_ONNX_TRT version 1 Registered plugin creator - ::EfficientNMS_Explicit_TF_TRT version 1 Registered plugin creator - ::EfficientNMS_Implicit_TF_TRT version 1 Registered plugin creator - ::ProposalDynamic version 1 Registered plugin creator - ::Proposal version 1 Registered plugin creator - ::ProposalLayer_TRT version 1 Registered plugin creator - ::PyramidROIAlign_TRT version 1 Registered plugin creator - ::ResizeNearest_TRT version 1 Registered plugin creator - ::Split version 1 Registered plugin creator - ::SpecialSlice_TRT version 1 Registered plugin creator - ::InstanceNormalization_TRT version 1 Registered plugin creator - ::InstanceNormalization_TRT version 2 Registered plugin creator - ::CoordConvAC version 1 Registered plugin creator - ::DecodeBbox3DPlugin version 1 Registered plugin creator - ::GenerateDetection_TRT version 1 Registered plugin creator - ::MultilevelCropAndResize_TRT version 1 Registered plugin creator - ::MultilevelProposeROI_TRT version 1 Registered plugin creator - ::NMSDynamic_TRT version 1 Registered plugin creator - ::PillarScatterPlugin version 1 Registered plugin creator - ::VoxelGeneratorPlugin version 1 Registered plugin creator - ::MultiscaleDeformableAttnPlugin_TRT version 1 Using cublas as a tactic source Using cuDNN as a tactic source Deserialization required 402759 microseconds. Using cublas as a tactic source Using cuDNN as a tactic source Total per-runner device persistent memory is 1420800 Total per-runner host persistent memory is 108288 Allocated activation device memory of size 65997824 20ms
> > > Now I have the correct reasoning picture
> > 
> > 
> > yes ! if this reop is helpful for your work, Could you give me a free star
> 
> of course

thanks!!!
