### ISSUE TITLE
nvidia-tensorrt 报错

### ISSUE THREAD

**Issue by monkeycc** [Linaom1214/TensorRT-For-YOLO-Series#42]
anaconda python3.7
win11

只能linux？
win有没办法的？

```
 pip install nvidia-pyindex
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: nvidia-pyindex in d:\anaconda3\lib\site-packages (1.0.9)

(yolov7) PS D:\> pip install --upgrade nvidia-tensorrt

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com
Collecting nvidia-tensorrt
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b8/a3/3da2bd25b6243d7a19b6c08c0e92f7c04f9863e70d213fee3141d574dccb/nvidia-tensorrt-0.0.1.dev5.tar.gz (7.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mm\AppData\Local\Temp\pip-install-86qwtshw\nvidia-tensorrt_2f4607caa6e542a3bcb5c92aa2e31d0e\setup.py", line 150, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.

      This package can be installed as:
      ```
      $ pip install nvidia-pyindex
      $ pip install nvidia-tensorrt
      ```
      ###########################################################################################

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Linaom1214** [comment]
> anaconda python3.7 win11
> 
> 只能linux？ win有没办法的？
> 
> ```
>  pip install nvidia-pyindex
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com
> Requirement already satisfied: nvidia-pyindex in d:\anaconda3\lib\site-packages (1.0.9)
> 
> (yolov7) PS D:\> pip install --upgrade nvidia-tensorrt
> 
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com
> Collecting nvidia-tensorrt
>   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b8/a3/3da2bd25b6243d7a19b6c08c0e92f7c04f9863e70d213fee3141d574dccb/nvidia-tensorrt-0.0.1.dev5.tar.gz (7.9 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [17 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\mm\AppData\Local\Temp\pip-install-86qwtshw\nvidia-tensorrt_2f4607caa6e542a3bcb5c92aa2e31d0e\setup.py", line 150, in <module>
>           raise RuntimeError(open("ERROR.txt", "r").read())
>       RuntimeError:
>       ###########################################################################################
>       The package you are trying to install is only a placeholder project on PyPI.org repository.
>       This package is hosted on NVIDIA Python Package Index.
> 
>       This package can be installed as:
>       ```
>       $ pip install nvidia-pyindex
>       $ pip install nvidia-tensorrt
>       ```
>       ###########################################################################################
> 
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> ```

step1 

```
pip install nvidia-pyindex
```
step2

```
pip install nvidia-tensorrt
```

**Comment by amnesia-3** [comment]
(yolov5) PS C:\Users\abc> pip install nvidia-pyindex
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: nvidia-pyindex in d:\anaconda\envs\yolov5\lib\site-packages (1.0.9)
(yolov5) PS C:\Users\abc> pip install nvidia-tensorrt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting nvidia-tensorrt
  Downloading nvidia-tensorrt-0.0.1.dev5.tar.gz (7.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\abc\AppData\Local\Temp\pip-install-oag1ljv6\nvidia-tensorrt_e2d85ac2e9664aed92598f767fa07e53\setup.py", line 150, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.

      This package can be installed as:
      ```
      $ pip install nvidia-pyindex
      $ pip install nvidia-tensorrt
      ```
      ###########################################################################################

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
