### ISSUE TITLE
Getting an issue with int8 precession

### ISSUE THREAD

**Issue by PavanAchari** [Linaom1214/TensorRT-For-YOLO-Series#45]
Hi
First of all Thankyou very much for sharing this with us
I am getting an issue when I am trying to convert the Yolov6 model weights to Tensorrt with int8 precession the conversion has been done but the detections are not working
and also I have tried to reduce the threshold to 0.001 still the detections are not working 
and when I convert that model with fp32,fp16 is working fine 
Could you please help me with this 

Thanks & Regards,
Pavan

**Comment by Linaom1214** [comment]
> 

Use the coco dataset?

**Comment by PavanAchari** [comment]
It's a custom dataset I have used

**Comment by xiaohui0225** [comment]
I have the same problem， too.  And I used COCO datasets as the calibration dataset. And tested different "--calib_num_images". No matter how hard I try, the detections are not working.

**Comment by Linaom1214** [comment]
> I have the same problem， too. And I used COCO datasets as the calibration dataset. And tested different "--calib_num_images". No matter how hard I try, the detections are not working.

Thanks for your feedback, I will try to troubleshoot this as soon as possible

**Comment by Linaom1214** [comment]
> I have the same problem， too. And I used COCO datasets as the calibration dataset. And tested different "--calib_num_images". No matter how hard I try, the detections are not working.

which model?

**Comment by Linaom1214** [comment]
@xiaohui0225 @PavanAchari 

https://github.com/Linaom1214/TensorRT-For-YOLO-Series/blob/8c9189ef6d50ea1c36b1232b172f3221847e5791/image_batch.py#L154


change the code 

```python
return  image / 255. , scale 

```

**Comment by xiaohui0225** [comment]
> 
YOLOv7
