### ISSUE TITLE
tensorrt 7版本

### ISSUE THREAD

**Issue by XiaoJiNu** [Linaom1214/TensorRT-For-YOLO-Series#46]
您好，能否支持tensorrt 7版本，某些场景无法使用tensorrt8

**Comment by Linaom1214** [comment]
> 您好，能否支持tensorrt 7版本，某些场景无法使用tensorrt8

end2end don't support tensorrt7, norm style is support tensorrt7

**Comment by XiaoJiNu** [comment]
thank you
