### ISSUE TITLE
nms插件

### ISSUE THREAD

**Issue by chenjl12** [Linaom1214/TensorRT-For-YOLO-Series#54]
nms是指非极大值抑制吗？请问为什么分开使用nms和不使用nms两个版本，如果不使用nms岂不是会得到很多重复的框？

**Comment by Linaom1214** [comment]
> nms是指非极大值抑制吗？请问为什么分开使用nms和不使用nms两个版本，如果不使用nms岂不是会得到很多重复的框？

nms 版本是指 在trt模型中包含nms 不需要额外的后处理
