### ISSUE TITLE
段错误问题

### ISSUE THREAD

**Issue by JACKYLUO1991** [Linaom1214/TensorRT-For-YOLO-Series#55]
您好，按照您给的指南成功转换模型后显示段错误，貌似是资源没有释放问题...我该如何解决呢？

**Comment by Linaom1214** [comment]
https://github.com/Linaom1214/TensorRT-For-YOLO-Series/blob/91333dc55cf580efe766be4c6aab2ab7b22421d6/export.py#L259
 
尝试更大的工作空间

**Comment by JACKYLUO1991** [comment]
@Linaom1214 已解决，多谢多谢
