### ISSUE TITLE
请教大佬，onnx转 trt出现 No importer registered for op: NonMaxSuppression

### ISSUE THREAD

**Issue by zhuimeng2080** [Linaom1214/TensorRT-For-YOLO-Series#62]
如题，采用的tensorrt 7.2版本把 onnx转 trt, 出现No importer registered for op: NonMaxSuppression是什么原因

**Comment by Linaom1214** [comment]
> ，采用的tensorrt 7.2版本把 onnx转 trt, 出现No importer regi

trt8 不支持efficient nms插件
