### ISSUE TITLE
您好，NMS能够使用TensorRT加速吗？

### ISSUE THREAD

**Issue by 1994sugar** [Linaom1214/TensorRT-For-YOLO-Series#64]

**Comment by 1994sugar** [comment]
> 这个工作就在做这个啊

大佬，niupee，具体原理是将NMS封装为网络层先转成onnx再转成tensorRT吗？

**Comment by Linaom1214** [comment]
> 

不是的， 导出的onnx模型是不包含nms组件的， 通过TRT的API把NMS注册到网络中

**Comment by 1994sugar** [comment]
> > 
> 
> 不是的， 导出的onnx模型是不包含nms组件的， 通过TRT的API把NMS注册到网络中

明白，感谢大佬的工作

**Comment by 1994sugar** [comment]
> > 
> 
> 不是的， 导出的onnx模型是不包含nms组件的， 通过TRT的API把NMS注册到网络中

大佬，学习TensorRT有相关资料推荐吗？
