### ISSUE TITLE
create_network（） issue

### ISSUE THREAD

**Issue by charming2992** [Linaom1214/TensorRT-For-YOLO-Series#65]
您好，按照步骤导出了onnx文件
现在使用您的export.py转换成.trt文件时候报错
python export.py -o /home/huangjiaming/1/yolov7/runs/train/clt_2_train/weights/best.onnx -e 1/yolov7-tiny-clt2.trt --end2end

Traceback (most recent call last):
  File "export.py", line 291, in <module>
    main(args)
  File "export.py", line 251, in main
    builder.create_network(args.onnx, args.end2end, args.conf_thres, args.iou_thres, args.max_det)
  File "export.py", line 155, in create_network
    bs, num_boxes, temp = previous_output
TypeError: cannot unpack non-iterable tensorrt.tensorrt.ITensor object
（trnsorrt的版本是8.4）

**Comment by charming2992** [comment]
然后不使用end2end的话是可以导出的，但是使用trt.py推理时的检测效果和.pt文件推理的结果相差很大，效果比较差

**Comment by Linaom1214** [comment]
> 然后不使用end2end的话是可以导出的，但是使用trt.py推理时的检测效果和.pt文件推理的结果相差很大，效果比较差

建议使用ONNX检查模型， 保证模型只有一个输出且不包含NMS op

**Comment by charming2992** [comment]
> > 然后不使用end2end的话是可以导出的，但是使用trt.py推理时的检测效果和.pt文件推理的结果相差很大，效果比较差
> 
> 建议使用netron 检查ONNX模型， 保证模型只有一个输出且不包含NMS op

yolov7不是有三个输出吗？保证一个输出是什么意思

**Comment by Linaom1214** [comment]
> > > 然后不使用end2end的话是可以导出的，但是使用trt.py推理时的检测效果和.pt文件推理的结果相差很大，效果比较差
> > 
> > 
> > 建议使用netron 检查ONNX模型， 保证模型只有一个输出且不包含NMS op
> 
> yolov7不是有三个输出吗？保证一个输出是什么意思

包含解码过程的ONNX模型 只有一个输出时本项目的代码才能起作用

**Comment by Viki-researcher** [comment]
> 

在使用yolov7的export.py转成onnx时，不要加end2end参数，加了就会遇到这个问题

**Comment by Linaom1214** [comment]
> > 
> 
> 在使用yolov7的export.py转成onnx时，不要加end2end参数，加了就会遇到这个问题


your can try the code in **examples..ipynb** in colab.   https://github.com/Linaom1214/TensorRT-For-YOLO-Series/blob/main/Examples.ipynb this may help you.
