### ISSUE TITLE
Exporting yolov7-seg/yolov7-mask to TRT?

### ISSUE THREAD

**Issue by AlbertoOddness** [Linaom1214/TensorRT-For-YOLO-Series#66]
First, thanks for the repo! I've used it successfully to export yolov7 models to TRT and they work very well.

I am interested in exporting a segmentation/mask model to TRT. Reading https://github.com/WongKinYiu/yolov7/issues/856#issue-1387209543 I can see the model can be at least exported to ONNX. Does this repo support exporting mask/segmentation models to TRT?

Thanks!

**Comment by Linaom1214** [comment]
> First, thanks for the repo! I've used it successfully to export yolov7 models to TRT and they work very well.
> 
> I am interested in exporting a segmentation/mask model to TRT. Reading [WongKinYiu/yolov7#856 (comment)](https://github.com/WongKinYiu/yolov7/issues/856#issue-1387209543) I can see the model can be at least exported to ONNX. Does this repo support exporting mask/segmentation models to TRT?
> 
> Thanks!

now don't support,  i will consider after

**Comment by AlbertoOddness** [comment]
Thank you for your reply :) I'll keep an eye out for that!
