### ISSUE TITLE
yolox序列化后检测不到目标

### ISSUE THREAD

**Issue by jia0511** [Linaom1214/TensorRT-For-YOLO-Series#71]
通过你的介绍，修改了input output name Cpp代码，没有检测框

**Comment by Linaom1214** [comment]
> 通过你的介绍，修改了input output name Cpp代码，没有检测框

参考这个修改C++的代码
https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/11#issuecomment-1213933336

**Comment by jia0511** [comment]
我试下

**Comment by jia0511** [comment]
使用YOLOX模型时 请注释掉

    padded_img = padded_img[:, :, ::-1]
    padded_img /= 255.0
目前python代码通过注释上面两行已经运行成功，但是C++代码还是有问题，end2end或者norm都不正常，请问如何修改？
