### ISSUE TITLE
An issue on building a TensorRT engine on Jetson device

### ISSUE THREAD

**Issue by rose-jinyang** [Linaom1214/TensorRT-For-YOLO-Series#73]
Hello
How are you?
Thanks for contributing to this project.
I am going to use your repo on Jetson (JetPack 4.6.1)
The environment on the Jetson is:
Python 3.6.9
CUDA: 10.2
cuDNN: 8.2.1.32
TensorRT: 8.2.1.8

I got a yolov7-tiny.onnx model from yolov7 official repo as your guide in this repo.
I met an issue when exporting tensorrt engine from onnx model by using the script "export.py" on the jetson device.
![image](https://user-images.githubusercontent.com/47862419/206999464-04222306-b09e-4adb-8e41-543d6c0b7f16.png)
Could u guide me to fix it?
Thanks

**Comment by rose-jinyang** [comment]
I found the reason of the above issue.
The deprecated functions was replaced with new functions for the higher version of TensorRT.
BTW:
The TensorRT engine embedded with EfficientNet_NMS plugin does NOT work correctly on TensorRT 8.2.1.8.
I debugged the code and found the scores are negative values.
Can u run the TRT engine embedded with EfficientNet_NMS plugin on TRT 8.2.1.8?

**Comment by Linaom1214** [comment]
Please upgrade to the  TensorRT version greater than 8.4. It should be noted that TRT serialization files are not reusable across different devices.

**Comment by dlavrantonis** [comment]
Looks like this is a showstopper for Jetson Nano. Highest installable version is 8.2.1.9 - the version that comes with the latest JetPack.

As I understood from searching in nvidia forums, there is no plan to support Jetson Nano with a newer Jetpack. 
https://developer.nvidia.com/embedded/jetpack-archive (<--- no support of JetPack 5.x.x for Jetson Nano)

Also, there is no version of TensorRT for aarch64/cuda 10.2/ubuntu 18.04
https://developer.nvidia.com/nvidia-tensorrt-8x-download


Have a look at this discussion. Its apparent that nVidia has abandoned Jetson Nano:
https://forums.developer.nvidia.com/t/jetpack-5-0-2/223564/26

If someone finds a way to install a later version of TensorRT on Jetson Nano, feel please free to share the way

What can be found in the latest JetPack in detail:
 - NVIDIA Jetson Nano (Developer Kit Version)
   * Jetpack UNKNOWN [L4T 32.7.3]
   * NV Power Mode: MAXN - Type: 0
   * jetson_stats.service: active
 - Libraries:
   * CUDA: 10.2.300
   * cuDNN: 8.2.1.32
   * TensorRT: 8.2.1.9
   * Visionworks: 1.6.0.501
   * OpenCV: 4.5.4 compiled CUDA: YES
   * VPI: ii libnvvpi1 1.2.3 arm64 NVIDIA Vision Programming Interface library
   * Vulkan: 1.2.70

**Comment by tirelo3** [comment]
on this issue here https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/70

He seeems to have managed to convert to trt on jetson nano, .He might have the answers.

**Comment by AidanAbramson** [comment]
Hey! as someone who has encountered this issue while trying to convert on a Jetson NX w jetpack 4.6 (TRT 8.0.1), all you have to do is erase line 109 ad uncomment line 110. Although it says it's deprecated, it still produces the result.

**Comment by AidanAbramson** [comment]
> I found the reason of the above issue. The deprecated functions was replaced with new functions for the higher version of TensorRT. BTW: The TensorRT engine embedded with EfficientNet_NMS plugin does NOT work correctly on TensorRT 8.2.1.8. I debugged the code and found the detected scores are negative values. Can u run the TRT engine embedded with EfficientNet_NMS plugin on TRT 8.2.1.8?

@rose-jinyang I get the same negative confidence values. Do you know what TRT version 100% work? Thanks.
