### ISSUE TITLE
Negative Confidence

### ISSUE THREAD

**Issue by AidanAbramson** [Linaom1214/TensorRT-For-YOLO-Series#79]
Hi,

After using this repository to convert yolov7 to trt and it working for a while. Suddenly whenever I convert it again, the model returns detections with negative confidence and ~70% of images have double detections exactly on top of eachother, making me suspect the problem comes from the NMS layer... Does anyone experience the same problem, or perhaps has and has a solution? Thanks!

**Comment by EdisionWew** [comment]
> Hi,
> 
> After using this repository to convert yolov7 to trt and it working for a while. Suddenly whenever I convert it again, the model returns detections with negative confidence and ~70% of images have double detections exactly on top of eachother, making me suspect the problem comes from the NMS layer... Does anyone experience the same problem, or perhaps has and has a solution? Thanks!

Have you solved this problem？I met it too.

**Comment by Linaom1214** [comment]
@AidanAbramson  https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/93#issuecomment-1522719591
