### ISSUE TITLE
Cannot find binding of given name: image_arrays

### ISSUE THREAD

**Issue by pipidx** [Linaom1214/TensorRT-For-YOLO-Series#82]
I got this below error after

**Comment by pipidx** [comment]
running ./yolo -model_path  yolov8s.trt   -image_path ../../../src/2.jpeg 

model size: 35323744
Registered plugin creator - ::GridAnchor_TRT version 1
Registered plugin creator - ::GridAnchorRect_TRT version 1
Registered plugin creator - ::NMS_TRT version 1
Registered plugin creator - ::Reorg_TRT version 1
Registered plugin creator - ::Region_TRT version 1
Registered plugin creator - ::Clip_TRT version 1
Registered plugin creator - ::LReLU_TRT version 1
Registered plugin creator - ::PriorBox_TRT version 1
Registered plugin creator - ::Normalize_TRT version 1
Registered plugin creator - ::ScatterND version 1
Registered plugin creator - ::RPROI_TRT version 1
Registered plugin creator - ::BatchedNMS_TRT version 1
Registered plugin creator - ::BatchedNMSDynamic_TRT version 1
Registered plugin creator - ::FlattenConcat_TRT version 1
Registered plugin creator - ::CropAndResize version 1
Registered plugin creator - ::DetectionLayer_TRT version 1
Registered plugin creator - ::EfficientNMS_ONNX_TRT version 1
Registered plugin creator - ::EfficientNMS_TRT version 1
Registered plugin creator - ::Proposal version 1
Registered plugin creator - ::ProposalLayer_TRT version 1
Registered plugin creator - ::PyramidROIAlign_TRT version 1
Registered plugin creator - ::ResizeNearest_TRT version 1
Registered plugin creator - ::Split version 1
Registered plugin creator - ::SpecialSlice_TRT version 1
Registered plugin creator - ::InstanceNormalization_TRT version 1
Using cublasLt a tactic source
Using cuDNN as a tactic source
Deserialization required 844096 microseconds.
3: Cannot find binding of given name: image_arrays
3: [engine.cpp::getBindingDimensions::1197] Error Code 3: Internal Error (Parameter check failed at: runtime/api/engine.cpp::getBindingDimensions::1197, condition: bindIndex >= 0 && bindIndex < getNbBindings()
)
Using cublasLt a tactic source
Using cuDNN as a tactic source
Total per-runner device memory is 22731776
Total per-runner host memory is 202192
Allocated activation device memory of size 27394560
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.4) /workspace/opencv-4.5/opencv/modules/imgproc/src/resize.cpp:4054: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'

Aborted (core dumped)

**Comment by pipidx** [comment]
Hello guys, do you have any ideas what I have to deal with?

**Comment by Linaom1214** [comment]
> Hello guys, do you have any ideas what I have to deal with?

@pipidx  refer this doc https://github.com/Linaom1214/TensorRT-For-YOLO-Series/blob/main/cpp/README.MD , and
 the source code of yolov8. https://github.com/ultralytics/ultralytics/blob/aecd17d455d71dab12069e4b5aa2ffad4b9b94fe/ultralytics/yolo/engine/exporter.py#L292

**Comment by pipidx** [comment]
@Linaom1214 thank you, I will try it again.

**Comment by shubhangi0107** [comment]
Need to change 
const char* INPUT_BLOB_NAME = "image_arrays";
to
const char* INPUT_BLOB_NAME = "images";

**Comment by study123zh** [comment]
Thank you for your help, but now there is a new error, Cannot find binding of given name: outputs。
i look forward to your reply

发自我的iPhone


------------------ Original ------------------
From: shubhangi0107 ***@***.***&gt;
Date: Fri,Mar 24,2023 2:29 PM
To: Linaom1214/TensorRT-For-YOLO-Series ***@***.***&gt;
Cc: study123zh ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Linaom1214/TensorRT-For-YOLO-Series] Cannot find binding ofgiven name: image_arrays (Issue #82)





 
Need to change
 const char* INPUT_BLOB_NAME = "image_arrays";
 to
 const char* INPUT_BLOB_NAME = "images";
