### ISSUE TITLE
Yolo v8 conversion model, no output during inference

### ISSUE THREAD

**Issue by andreazuna89** [Linaom1214/TensorRT-For-YOLO-Series#85]
Hi! I am currently trying your repo for converting a yolo v8 model (yolov8s.pt) using a Jetson Orin. I have been trying the export.py script with both fp16 and fp32 type conversion. The model is converted but when I do inference with the produced engine I get an output always containing zeros and no detection is produced. Can you help me to understand where is the issue?

Thanks a lot
Andrea

**Comment by Linaom1214** [comment]
> Hi! I am currently trying your repo for converting a yolo v8 model (yolov8s.pt) using a Jetson Orin. I have been trying the export.py script with both fp16 and fp32 type conversion. The model is converted but when I do inference with the produced engine I get an output always containing zeros and no detection is produced. Can you help me to understand where is the issue?
> 
> Thanks a lot Andrea

Now the code for yolov8 has some error, I will update in next version.

**Comment by Linaom1214** [comment]
I update the repo, please enjoy !
