### ISSUE TITLE
Class agnostic NMS

### ISSUE THREAD

**Issue by PallottaEnrico** [Linaom1214/TensorRT-For-YOLO-Series#87]
Hi, is there a way to export my yolov8n.onnx to a TensorRT engine that includes **class agnostic nms**?

**Comment by dnns92** [comment]
see: https://forums.developer.nvidia.com/t/class-agnostic-nms-plugin/237320

**Comment by Linaom1214** [comment]
https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/93#issuecomment-1522719591
