### ISSUE TITLE
wrong confidence score (negative confidence score) on Jetson Nano inference

### ISSUE THREAD

**Issue by jet-c-21** [Linaom1214/TensorRT-For-YOLO-Series#98]
I use the following command got different result on different result:
```
python3 trt.py -e yolov8n.trt  -i src/1.jpg -o yolov8n-1.jpg --end2end
```

Inference result on GTX 1060:
![](https://hackmd.io/_uploads/H1UB4s542.jpg)
```
print(final_boxes, final_scores, final_cls_inds)
[[377.    57.75 907.   708.25]] [0.77539062] [0.]
```

Inference result on Jetson Nano (Tegra X1)
![](https://hackmd.io/_uploads/HkbiHo543.jpg)
```
print(final_boxes, final_scores, final_cls_inds)
[[ 377.   58.  907.  708.]] [-0.22753906] [ 0.]
```

### The bounding box coordinates appear to align quite closely; however, the confidence score appears to be suffering from a conversion error. Do I need to do additional settings during the ONNX to TensorRT transformation phase?

**Comment by Linaom1214** [comment]
> I use the following command got different result on different result:
> 
> ```
> python3 trt.py -e yolov8n.trt  -i src/1.jpg -o yolov8n-1.jpg --end2end
> ```
> 
> Inference result on GTX 1060: ![](https://camo.githubusercontent.com/ce9ee0e274b81393616c52093c59c2237569b430107ddead04cc25c66b26b9d2/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f4831554234733534322e6a7067)
> 
> ```
> print(final_boxes, final_scores, final_cls_inds)
> [[377.    57.75 907.   708.25]] [0.77539062] [0.]
> ```
> 
> Inference result on Jetson Nano (Tegra X1) ![](https://camo.githubusercontent.com/5d764ebebd77eced6f739df0199fee4026189d81ba6008a98ca2eef0c105a15b/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f486b6269486f3534332e6a7067)
> 
> ```
> print(final_boxes, final_scores, final_cls_inds)
> [[ 377.   58.  907.  708.]] [-0.22753906] [ 0.]
> ```
> 
> ### The bounding box coordinates appear to align quite closely; however, the confidence score appears to be suffering from a conversion error. Do I need to do additional settings during the ONNX to TensorRT transformation phase?

the error casue by nms plugin, recommend use fp32.

```
python export.py -o yolov8s.onnx -e yolov8s.trt --end2end --v8 -p fp32
```

**Comment by Linaom1214** [comment]
https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/93 refer this
